language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: G/bsXVElqPi/fqU2KPS2u1zGruh1yTpM44YXiFeLz7fnGFW+voavWCQPsRPHkJPycQt4+f+xgnBbIo/lFHh9q34Ywt23TkcaYHmvqrC/2IZi2MNxxKr5Y16g/1cSn8U11wpznaLYGmrxxvVIxCvs93Lx57az1IZ4XDNQUVyaJv8S2d4mkzTUaOzpJ2z3Q0emRlQkZdXvTxTkOrA0tVYlV+VawDm9M2IkSRWOOhJAUIDKYfnphJGQJw2A1pA//iFSQcbJ25++SZUgD3TKoENUfSvbxr4nP13+L8w3ihsD4bqG4Txm82znZvdwMbzavIX9WTU9k0/c/35mGuU8hL2b5wIHUNwQMPjKHIFUVVdHygSBlu7WiEE3dXNBiuTJC+J1UN20KRGdwyveLJ9bGJ7AvfDKsM74SUSTC/SzvoT2Q+RP/H/KEwjoJyL8EU8uMq+XwziZ2DUwbPhLABN4WlnvuVKd67fVDD1lrUzhu6Exxxxinl3/OK9+aKCPDjIKTW8MOpbGRh6PWJyR2EYuzBbL0QlMtQrChq4SwyGqtemw3VXeYg5V908eOUFPy8kDc3W3CFWI6/yEzUOIcuIerXgHyct5MYD1z67mKbj8IPIGuSYLwHYkUsUJ2Hv5J11UySNt86AWMfPLJLXhO6XyAsC70Ljpp+9SVzx59fDbmWTWvpQ=
  app: viewing-party-m3
  on:
    repo: cunninghamge/viewing_party
    branch: main
  run: rails db:migrate
