language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: L2xnpWxc5ohxUO7KHxdpuVhw3hwscWuCMoTX9k4dg4jU+Ta+dlOxBxhAHGF5rALW8v4EN9ckC23aGx18fUMlTuRkuzI9VcGKh0G29DO2Yrz6wKgL+ST0m1r0HlU28ei8C6sJD8NcnoqPU1ih+BznXI0+JxAMk2htVpG2UsCbF8SpDRQ+oXwFpo33DN2/QaOXaaFk1DVt+QdMIJcN6XLJaao8Ti9eTUUAJ2oVQUedlM/CLPLzkRSWC2NGoL97/oxfbWJq8jd8n5pk2sDJUYkBZFdiZCbCLTHkbAXg5dFUBI1V2RCVh35LE+k1Nhc1MRrvVBp5Exnd9xTkalPorDhvrZogFU5ytf8FqxC5QyPygle2IBT8kSZeDHvZAbckonu4ywQ9nxj5b/j1qFx39BvDQ6GARdCCjVkijDYur2k8FJ6+3ti0jLo/94JiZvbgMnjv0Rn54CemzuP77Hh9qGBrOtflwbS0l9lp+n1X8sPvAiD2wIk4ecV4PGRVlpLSr7swFpVMTlp9FhbJ0O3+L6jc3v2gqsH/jw2tZ5HSMeMx9U7zM4rGqcmskdKSCMa/LDB2E4vnGOiGXT37ZHY0WNVICtTULgcr1zi6AfvepJ2DjhazB9e/rn35KJ8Ro5LY/1/JDGl7IV1s9m6AzIjlW8bfUpSI0QYE1vXSONe4J8bdBNQ=
  app: viewing-party-m3
  on:
    repo: cunninghamge/viewing_party
    branch: main
  run: rails db:migrate
